-- Tests for ":show imports" and import/:module
:show imports
import Prelude
:show imports
:!printf "== map in scope due to explicit 'import Prelude'\n"
:t map
import Prelude ()
:show imports
:!printf "== still in scope, 'import Prelude ()' is subsumed by 'import Prelude'\n"
:t map
:module -Prelude
:show imports
:!printf "== still in scope, implicit import of Prelude\n"
:t map
import Prelude ()
:show imports
:!printf "== not in scope now\n"
:t map

:module -Prelude
:show imports
:load ghci038.hs

:t x
:show imports
:!printf ":m -Foo\n"
:m -Foo
:show imports
:t x
:!printf ":m +*Foo\n"
:m +*Foo
:show imports
:t x

import Prelude
:show imports
import Data.List hiding (nub)
:show imports
import qualified Data.List as Q
:show imports
:m -Data.List
:show imports
