:l ghci025
System.IO.putStrLn "-- test :browse! functionality"
System.IO.putStrLn ":browse! *T"
:browse! *T
System.IO.putStrLn ":browse! T"
:browse! T
:set -fprint-explicit-foralls
System.IO.putStrLn ":browse! T -- with -fprint-explicit-foralls"
:browse! T

System.IO.putStrLn "-- test :browse! <target> relative to different contexts"
:set -fforce-recomp
-- ToDo: this will go wrong in parallel
:! cp ../prog001/D1.hs ../prog001/D.hs
:l ../prog001/D.hs
:add ../prog001/C.hs
System.IO.putStrLn ":browse! C -- from *C>"
:browse! C
:add ../prog001/B.hs
System.IO.putStrLn ":browse! C -- from *B>, after :add B"
:browse! C
:m *C
System.IO.putStrLn ":browse! C -- from *C>, after :m *C"
:browse! C
:m *D
System.IO.putStrLn ":browse! C -- from *D>, after :m *D"
:browse! C
