:set -XPatternGuards -XArrows -XRankNTypes

:t lookup
:t undefined :: (forall a. a -> a) -> a
:t () >- () -< () >>- () -<< ()
let fun foo | True <- () = ()

:set -fprint-unicode-syntax

:t lookup
:t undefined :: (forall a. a -> a) -> a
:t () >- () -< () >>- () -<< ()
let fun foo | True <- () = ()

:set -fno-print-unicode-syntax

:t lookup
:t undefined :: (forall a. a -> a) -> a
:t () >- () -< () >>- () -<< ()
let fun foo | True <- () = ()
