module Rules.Clean (cleanRules) where

import Base
import Context
import Package
import Rules.Actions
import Rules.Generate
import Settings.Packages
import Settings.Paths
import Settings.User
import Stage

cleanRules :: Rules ()
cleanRules = do
    "clean" ~> do
        forM_ [Stage0 ..] $ removeDirectory . (buildRootPath -/-) . stageString
        removeDirectory programInplacePath
        removeDirectory "inplace/lib"
        removeDirectory derivedConstantsPath
        forM_ includesDependencies $ \file -> do
            putBuild $ "| Remove " ++ file
            removeFileIfExists file
        putBuild $ "| Remove files generated by ghc-cabal..."
        forM_ knownPackages $ \pkg ->
            forM_ [Stage0 ..] $ \stage -> do
                let dir = pkgPath pkg -/- contextDirectory (vanillaContext stage pkg)
                quietly $ removeDirectory dir
        putBuild $ "| Remove Hadrian files..."
        removeFilesAfter buildRootPath ["//*"]
        putSuccess $ "| Done. "
