# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.6 2005/06/07 10:58:31 simonmar Exp $
# (c) Simon Marlow 1999-2000

TOP=..
include $(TOP)/mk/boilerplate.mk

SRC_HC_OPTS    += -fglasgow-exts -package util -package data -package text -cpp -package lang
HS_PROG		= nofib-analyse

include $(TOP)/mk/target.mk
