SRC_HC_OPTS        = -O0 -H64m
GhcStage1HcOpts    = -O
GhcStage2HcOpts    = -O0
GhcLibHcOpts       = -O0
BUILD_PROF_LIBS    = NO
SplitObjs          = NO
HADDOCK_DOCS       = NO
BUILD_SPHINX_HTML  = NO
BUILD_SPHINX_PDF   = NO
BUILD_MAN          = NO
