SRC_HC_OPTS        = -O0 -H64m -fllvm
GhcStage0HcOpts    = -O
GhcStage1HcOpts    = -O0
GhcLibHcOpts       = -O
BUILD_PROF_LIBS    = NO
SplitSections      = NO
HADDOCK_DOCS       = NO
BUILD_SPHINX_HTML  = NO
BUILD_SPHINX_PDF   = NO
BUILD_MAN          = NO
