resolver: nightly-2017-11-01
packages:
- Cabal/
- cabal-install/
- cabal-testsuite/
extra-deps:
  - resolv-0.1.1.1
nix:
  packages:
  - autoconf
  - automake
  - haskellPackages.happy
  - haskellPackages.alex
  - zlib
  - zlib.out
