variables:
  GIT_SSL_NO_VERIFY: "1"

before_script:
  - python3 .gitlab/fix-submodules.py
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - git checkout .gitmodules
  - "git fetch https://gitlab.haskell.org/ghc/ghc-performance-notes.git refs/notes/perf:refs/notes/perf || true"

stages:
  - full-build
  - cleanup # See Note [Cleanup on Windows]

############################################################
# Validation via Pipelines (Windows)
############################################################

.validate-windows:
  before_script:
    - git clean -xdf
    - git submodule foreach git clean -xdf

    # Use a local temporary directory to ensure that concurrent builds don't
    # interfere with one another
    - |
      mkdir tmp
      set TMP=%cd%\tmp
      set TEMP=%cd%\tmp

    - set PATH=C:\msys64\usr\bin;%PATH%
#    - python .gitlab/fix-submodules.py
#    - git submodule sync --recursive
#    - git submodule update --init --recursive
#    - git checkout .gitmodules
#    - "git fetch https://gitlab.haskell.org/ghc/ghc-performance-notes.git refs/notes/perf:refs/notes/perf || true"
#    - bash .gitlab/win32-init.sh
  after_script:
    - rd /s /q tmp
    - robocopy /np /nfl /ndl /e "%APPDATA%\cabal" cabal-cache
    - bash -c 'make clean || true'
  dependencies: []
  variables:
    FORCE_SYMLINKS: 1
  cache:
    paths:
      - cabal-cache
      - ghc-8.6.2
      - ghc-tarballs

validate-x86_64-windows:
  extends: .validate-windows
  stage: full-build
  # due to #16084
  allow_failure: true
  variables:
    GHC_VERSION: "8.6.2"
    LANG: "en_US.UTF-8"
  script:
    - |
  #    set MSYSTEM=MINGW64
  #    python boot
  #    bash -c './configure --enable-tarballs-autodownload GHC=`pwd`/toolchain/bin/ghc HAPPY=`pwd`/toolchain/bin/happy ALEX=`pwd`/toolchain/bin/alex'
  #  - bash -c "echo include mk/flavours/quick.mk > mk/build.mk"
  #  - bash -c "PATH=`pwd`/toolchain/bin:$PATH make -j`mk/detect-cpu-count.sh`"
  #  - |
  #    bash -c "make binary-dist TAR_COMP_OPTS=-1"
  #    mv ghc-*.tar.xz ghc.tar.xz
    - |
  #    git config user.email "ben+ghc-ci@smart-cactus.org"
  #    git config user.name "GHC GitLab CI"


  #  - bash -c "METRICS_FILE=`mktemp` && echo \$METRICS_FILE THREADS=`mk/detect-cpu-count.sh` JUNIT_FILE=../../junit.xml && .gitlab/push-test-metrics.sh"
    - bash -c "METRICS_FILE=`mktemp` && echo \$METRICS_FILE"

    
  cache:
    key: x86_64-windows
  tags:
    - x86_64-windows
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - ghc.tar.xz
      - junit.xml

# Note [Cleaning up after shell executor]
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# As noted in [1], gitlab-runner's shell executor doesn't clean up its working
# directory after builds. Unfortunately, we are forced to use the shell executor
# on Windows. To avoid running out of disk space we add a stage at the end of
# the build to remove the \GitLabRunner\builds directory. Since we only run a
# single build at a time on Windows this should be safe.
#
# [1] https://gitlab.com/gitlab-org/gitlab-runner/issues/3856

# See Note [Cleanup after shell executor]
cleanup-windows:
  stage: cleanup
  tags:
    - x86_64-windows
  when: always
  dependencies: []
  before_script:
    - echo "Time to clean up"
  script:
    - echo "Let's go"
  after_script:
    - set "BUILD_DIR=%CI_PROJECT_DIR%"
    - set "BUILD_DIR=%BUILD_DIR:/=\%"
    - echo "Cleaning %BUILD_DIR%"
    - cd \GitLabRunner
    # This is way more complicated than it should be:
    # See https://stackoverflow.com/questions/1965787
    - del %BUILD_DIR%\* /F /Q
    - for /d %%p in (%BUILD_DIR%\*) do rd /Q /S "%%p"
    - exit /b 0