spec:
  inputs:
    release:
      default: "no"
      description: Release pipeline
      options: [ "yes", "no" ]

---

variables:
  GIT_SSL_NO_VERIFY: "1"

  # Commit of ghc/ci-images repository from which to pull Docker images
  DOCKER_REV: 5df428b97c501f61f57587048d4bd15eba53e364

  # Sequential version number of all cached things.
  # Bump to invalidate GitLab CI cache.
  CACHE_REV: 12

  # Disable shallow clones; they break our linting rules
  GIT_DEPTH: 0

  # Always start with a fresh clone to avoid non-hermetic builds
  GIT_STRATEGY: clone

  # Overridden by individual jobs
  CONFIGURE_ARGS: ""

  # Overridden by individual jobs
  CONFIGURE_WRAPPER: ""

  GIT_SUBMODULE_STRATEGY: "normal"

  # GitLab recommends using https:, not ssh:, to clone submodules. See #25528.
  GIT_SUBMODULE_FORCE_HTTPS: 1

  # Makes ci.sh isolate CABAL_DIR
  HERMETIC: "YES"

  RELEASE_JOB: $[[ inputs.release ]]

  # Reduce XZ compression level for regular jobs (it is bumped to 9 for releases
  # and nightly jobs). In my experiments I've got the following bindist size in
  # the given time for each compression level (with the quick flavour):
  #
  #     XZ_OPT        Time    Size
  #     -9            4m06s   112 MB
  #     -8            4m00s   114 MB
  #     -7            3m50s   116 MB
  #     -6 (default)  3m40s   118 MB
  #     -5            2m47s   123 MB
  #     -4            1m57s   134 MB
  #     -3            1m03s   129 MB
  #     -2            49.73s  136 MB
  #     -1            37.72s  142 MB
  #     -0            34.40s  156 MB
  #
  XZ_OPT: "-1"
default:
  interruptible: true

stages:
  - test

# These jobs are generated by running the ./.gitlab/generate_jobs script
include: '.gitlab/jobs.yaml'
