# partain: probably not the right thing yet

all: configure

configure: configure.ac aclocal.m4
	rm -f configure.new
	autoconf configure.ac > configure.new \
		|| ( rm -f configure.new; exit 1 )
	rm -f configure
	mv configure.new configure
	chmod +x configure
	chmod -w configure
	if test -f config.status; then ./config.status --recheck; fi
	rm -f configure.new

CONFIG_H_IN = ghc/includes/config.h.in

config.h.in: configure.ac
	rm -f $(CONFIG_H_IN)
	autoheader configure.ac > $(CONFIG_H_IN) \
		|| ( rm -f $(CONFIG_H_IN); exit 1 )

# do something about autoheader
# do something about ghc-vs-nofib configure scripts
