# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.3 2005/03/02 16:39:58 ross Exp $

TOP=../..
include $(TOP)/mk/boilerplate.mk

H_FILES = $(wildcard *.h)

includedir = $(libdir)/include
INSTALL_INCLUDES = $(H_FILES)

DIST_CLEAN_FILES += HsNetworkConfig.h

include $(TOP)/mk/target.mk
