#-----------------------------------------------------------------------------
# $Id: Makefile,v 1.1 2000/04/05 10:11:55 simonmar Exp $
#
# (c) The GHC Team, 2000
#

TOP=../../..
include $(TOP)/mk/boilerplate.mk

override datadir=$(libdir)/icons
INSTALL_DATAS=$(wildcard *.xbm)

include $(TOP)/mk/target.mk
