{-# LANGUAGE MagicHash #-}
{-# OPTIONS_HADDOCK not-home #-}

-- |
-- Module      :  GHC.Num
-- Copyright   :  (c) The University of Glasgow 1994-2002
-- License     :  see libraries/base/LICENSE
--
-- Maintainer  :  ghc-devs@haskell.org
-- Stability   :  internal
-- Portability :  non-portable (GHC Extensions)
--
-- The 'Num' class and the 'Integer' type.
--

module GHC.Num
   ( Num(..)
   , subtract
   , quotRemInteger
   , integerFromNatural
   , integerToNaturalClamp
   , integerToNaturalThrow
   , integerToNatural
   , integerToWord#
   , integerToInt#
   , integerToWord64#
   , integerToInt64#
   , integerAdd
   , integerMul
   , integerSub
   , integerNegate
   , integerAbs
   , integerPopCount#
   , integerQuot
   , integerRem
   , integerDiv
   , integerMod
   , integerDivMod#
   , integerQuotRem#
   , integerEncodeFloat#
   , integerEncodeDouble#
   , integerGcd
   , integerLcm
   , integerAnd
   , integerOr
   , integerXor
   , integerComplement
   , integerBit#
   , integerTestBit#
   , integerShiftL#
   , integerShiftR#
   , integerFromWord#
   , integerFromWord64#
   , integerFromInt64#
   , Integer(..)
   , integerBit
   , integerCheck
   , integerCheck#
   , integerCompare
   , integerDecodeDouble#
   , integerDivMod
   , integerEncodeDouble
   , integerEq
   , integerEq#
   , integerFromAddr
   , integerFromAddr#
   , integerFromBigNat#
   , integerFromBigNatNeg#
   , integerFromBigNatSign#
   , integerFromByteArray
   , integerFromByteArray#
   , integerFromInt
   , integerFromInt#
   , integerFromWord
   , integerFromWordList
   , integerFromWordNeg#
   , integerFromWordSign#
   , integerGcde
   , integerGcde#
   , integerGe
   , integerGe#
   , integerGt
   , integerGt#
   , integerIsNegative
   , integerIsNegative#
   , integerIsOne
   , integerIsPowerOf2#
   , integerIsZero
   , integerLe
   , integerLe#
   , integerLog2
   , integerLog2#
   , integerLogBase
   , integerLogBase#
   , integerLogBaseWord
   , integerLogBaseWord#
   , integerLt
   , integerLt#
   , integerNe
   , integerNe#
   , integerOne
   , integerPowMod#
   , integerQuotRem
   , integerRecipMod#
   , integerShiftL
   , integerShiftR
   , integerSignum
   , integerSignum#
   , integerSizeInBase#
   , integerSqr
   , integerTestBit
   , integerToAddr
   , integerToAddr#
   , integerToBigNatClamp#
   , integerToBigNatSign#
   , integerToInt
   , integerToMutableByteArray
   , integerToMutableByteArray#
   , integerToWord
   , integerZero
   , naturalToWord#
   , naturalPopCount#
   , naturalShiftR#
   , naturalShiftL#
   , naturalAdd
   , naturalSub
   , naturalSubThrow
   , naturalSubUnsafe
   , naturalMul
   , naturalQuotRem#
   , naturalQuot
   , naturalRem
   , naturalAnd
   , naturalAndNot
   , naturalOr
   , naturalXor
   , naturalTestBit#
   , naturalBit#
   , naturalGcd
   , naturalLcm
   , naturalLog2#
   , naturalLogBaseWord#
   , naturalLogBase#
   , naturalPowMod
   , naturalSizeInBase#
   , Natural(..)
   , naturalBit
   , naturalCheck
   , naturalCheck#
   , naturalClearBit
   , naturalClearBit#
   , naturalCompare
   , naturalComplementBit
   , naturalComplementBit#
   , naturalEncodeDouble#
   , naturalEncodeFloat#
   , naturalEq
   , naturalEq#
   , naturalFromAddr
   , naturalFromAddr#
   , naturalFromBigNat#
   , naturalFromByteArray#
   , naturalFromWord
   , naturalFromWord#
   , naturalFromWord2#
   , naturalFromWordList
   , naturalGe
   , naturalGe#
   , naturalGt
   , naturalGt#
   , naturalIsOne
   , naturalIsPowerOf2#
   , naturalIsZero
   , naturalLe
   , naturalLe#
   , naturalLog2
   , naturalLogBase
   , naturalLogBaseWord
   , naturalLt
   , naturalLt#
   , naturalNe
   , naturalNe#
   , naturalNegate
   , naturalOne
   , naturalPopCount
   , naturalQuotRem
   , naturalSetBit
   , naturalSetBit#
   , naturalShiftL
   , naturalShiftR
   , naturalSignum
   , naturalSqr
   , naturalTestBit
   , naturalToAddr
   , naturalToAddr#
   , naturalToBigNat#
   , naturalToMutableByteArray#
   , naturalToWord
   , naturalToWordClamp
   , naturalToWordClamp#
   , naturalToWordMaybe#
   , naturalZero
   )
where

import GHC.Internal.Num
