# This is a Stack project-level configuration file. It allows Stack to build the
# project packages described by hadrian.cabal,
# ../utils/ghc-toolchain/ghc-toolchain.cabal and
# ../libraries/ghc-platform/ghc-platform.cabal.
#
# When Stack has been configured to build GHC from source (that is,
# compiler: ghc-git-<commit>-<flavour>), unless another snapshot is specified,
# Stack also uses this configuration file to specify the version of GHC that
# will be used to build GHC from source.

# GHC's configure script reports that GHC versions 9.10 and greater are required
# to build GHC from source:
snapshot: lts-24.20 # GHC 9.10.3

packages:
- '.'
- '../utils/ghc-toolchain'
- '../libraries/ghc-platform'

nix:
  enable: false
  packages:
  - autoconf
  - automake
  - gcc
  - git
  - ncurses
  - perl
  - ghc-toolchain

flags:
  directory:
    os-string: true # False, by default
  process:
    os-string: true # False, by default

extra-deps:
# Needed due to Hadrian's lower bound on Cabal >= 3.13:
- Cabal-3.14.2.0
- Cabal-syntax-3.14.2.0
# Needed due to Hadrian's lower bound on directory >= 1.3.9.0:
- directory-1.3.9.0
# Needed because process depends on directory, which has been pruned:
- process-1.6.26.1
