# GHC's configure script reports that GHC versions 9.6 and greater are required
# to build GHC from source.
resolver: lts-22.44 # GHC 9.6.7

packages:
- '.'
- '../utils/ghc-toolchain'
- '../libraries/ghc-platform'

nix:
   enable: false
   packages:
   - autoconf
   - automake
   - gcc
   - git
   - ncurses
   - perl
   - ghc-toolchain

extra-deps:
- Cabal-3.14.0.0
- Cabal-syntax-3.14.0.0

# needed due to Hadrian's lower bound on directory
- directory-1.3.9.0
- file-io-0.1.4
- filepath-1.4.300.2
- process-1.6.25.0
- unix-2.8.5.1
