# GHC's configure script reports that GHC versions 9.2 and greater are required
# to build GHC from source.
resolver: lts-20.26 # GHC 9.2.8

packages:
- '.'
- '../utils/ghc-toolchain'
- '../libraries/ghc-platform'

nix:
   enable: false
   packages:
   - autoconf
   - automake
   - gcc
   - git
   - ncurses
   - perl
   - ghc-toolchain

extra-deps:
- Cabal-3.14.0.0
- Cabal-syntax-3.14.0.0
