#-----------------------------------------------------------------------------
# $Id: Makefile,v 1.1 1997/12/19 12:22:06 simonm Exp $

TOP = ..
include $(TOP)/mk/boilerplate.mk

SUBDIRS = should_run

include $(TOP)/mk/target.mk


