:unset +s

-- first, tidy up:
:!rm -f *.hi *.o *~
:!cp C1.hs C.hs
:!cp D1.hs D.hs

-- load the program (all interpreted)
:load A.hs

-- reloading should do nothing
:reload

-- make sure `main' works
main

-- change a module + recompile
:!echo >> C.hs
:reload

-- make sure `main' still works
main

-- compile D & reload
:!"$HC" $HC_OPTS $ghciWayFlags -fforce-recomp -c D.hs
:reload
main

-- change D, recompile & reload
:!cp D2.hs D.hs
:!"$HC" $HC_OPTS $ghciWayFlags -fforce-recomp -c D.hs
:reload
:load A.hs

-- make sure we're picking up the new D, via B
:module B
g 42
