#include <stdio.h>
#include "Rts.h"
#include "OptParseTestUtil.h"

#define SAFE true
#define UNSAFE false

bool ERROR = false;

int main (int argc, char *argv[])
{

     printf("=== OptParseTest START ===\n");

     _TEST( "-?", HELP, NO_VAL(HELP));

     BOOL_FLAG_TEST(INSTALL_SIGNAL_HANDLERS);
     BOOL_FLAG_TEST(INSTALL_SEH_HANDLERS);
     BOOL_FLAG_TEST(GENERATE_STACK_TRACES);
     BOOL_FLAG_TEST(GENERATE_CRASH_DUMPS);
     BOOL_FLAG_TEST(NULL_EVENTLOG_WRITER);
     BOOL_FLAG_TEST(MACHINE_READABLE);
     BOOL_FLAG_TEST(DISABLE_OS_MEM_RET);
     BOOL_FLAG_TEST(INTERNAL_COUNTERS);

     _TEST( "--io-manager=native", IO_MANAGER_FLAG
          , ENUM_VAL(IO_MANAGER_FLAG, IO_MNGR_NATIVE));
     _TEST( "--io-manager=posix", IO_MANAGER_FLAG
          , ENUM_VAL(IO_MANAGER_FLAG, IO_MNGR_POSIX));
     _FAIL_TEST("--io-manager");
     _FAIL_TEST("--io-manager=");
     _FAIL_TEST("--io-manager=unknown-manager");
     _FAIL_TEST("--io-managerlgaks");

     VOID_FLAG_TEST(INFO);
     DOUBLE_FLAG_TEST(EVENTLOG_FLUSH_INTERVAL);
     VOID_FLAG_TEST(COPYING_GC);
     VOID_FLAG_TEST(NONMOVING_GC);

     STGWORD64_FLAG_TEST(LARGE_OBJ_ALLOC_AREA);
     STGWORD64_FLAG_TEST(MIN_ALLOC_AREA);
     STGWORD64_FLAG_TEST(IO_MANAGER_THREADS);
     STGWORD64_FLAG_TEST(NUMA);
     STGWORD64_TEST(NUMA, (StgWord64)~0, "--%s", rtsFlags[NUMA].longName);
     NATURAL_NUM_FLAG_TEST(DEBUG_NUMA, 0, MAX_NUMA_NODES);
     DOUBLE_FLAG_TEST(LONG_GC_SYNC);

     BOOL_FLAG_TEST(NO_AUTO_HEAP_SAMPLES);
     STGWORD64_FLAG_TEST(NURSERY_CHUNK_SIZE);
     VOID_FLAG_TEST(GC_BELL);
     DOUBLE_FLAG_TEST(COMPACT_GC);
     VOID_FLAG_TEST(USE_MARK_REGION);
     DOUBLE_FLAG_TEST(OLD_GEN_FACTOR);
     DOUBLE_FLAG_TEST(RETURN_DECAY_FACTOR);
     DOUBLE_FLAG_TEST(RETURN_DECAY_FACTOR);

     VOID_FLAG_TEST(DEBUG_SCHEDULER);
     VOID_FLAG_TEST(DEBUG_INTERPRETER);
     VOID_FLAG_TEST(DEBUG_WEAK);
     VOID_FLAG_TEST(DEBUG_GCCAFS);
     VOID_FLAG_TEST(DEBUG_GC);
     VOID_FLAG_TEST(DEBUG_NONMOVING_GC);
     VOID_FLAG_TEST(DEBUG_BLOCK_ALLOC);
     VOID_FLAG_TEST(DEBUG_SANITY);
     VOID_FLAG_TEST(DEBUG_ZERO_IN_GC);
     VOID_FLAG_TEST(DEBUG_STABLE);
     VOID_FLAG_TEST(DEBUG_PROF);
     VOID_FLAG_TEST(DEBUG_LINKER);
     VOID_FLAG_TEST(DEBUG_LINKER_VERBOSE);
     VOID_FLAG_TEST(DEBUG_APPLY);
     VOID_FLAG_TEST(DEBUG_STM);
     VOID_FLAG_TEST(DEBUG_SQUEEZE);
     VOID_FLAG_TEST(DEBUG_HPC);
     VOID_FLAG_TEST(DEBUG_SPARKS);
     VOID_FLAG_TEST(DEBUG_COMPACT);

     STGWORD64_FLAG_TEST(MAX_STACK_SIZE);
     STGWORD64_FLAG_TEST(STACK_CHUNK_SIZE);
     STGWORD64_FLAG_TEST(STACK_CHUNK_BUFFER_SIZE);
     STGWORD64_FLAG_TEST(STACK_INITIAL_SIZE);

     printf("\n=== OptParseTest END ===\n");
     return 0;
}
