-- Test out printing of integers in GHCi

-- With @ghc-bignum@, small integer literals get converted directly into
-- @IS i#@. This optimization means that small integers are always already
-- evaluated in the output for @:p@.

let smallNeg = -53 :: Integer
:f smallNeg

let smallPos = 89 :: Integer
:f smallPos

let zero = 0 :: Integer
:f zero

let largeNeg = -4123841823694876543987265438957349857349 :: Integer
:f largeNeg

let largePos =  5402398759384752938475029384750298347554 :: Integer
:f largePos

:q
