-- Test out printing of integers in GHCi

-- With @integer-gmp@, small integer literals get converted directly into
-- @S# i#@. This optimization means that small integers are always already
-- evaluated in the output for @:p@.
--
-- Since we want this test to work on @integer-simple@ too, we explicitly
-- force the literals.

let smallNeg = -53 :: Integer
:f smallNeg

let smallPos = 89 :: Integer
:f smallPos

let zero = 0 :: Integer
:f zero

let largeNeg = -4123841823694876543987265438957349857349 :: Integer
:f largeNeg

let largePos =  5402398759384752938475029384750298347554 :: Integer
:f largePos

:q
