-- printing of Showables

:set -XExistentialQuantification -XDeriveDataTypeable -XGeneralizedNewtypeDeriving
let f = Just (1.2::Float)
f
:p f

-- With @integer-gmp@, small integer literals get converted directly into
-- @S# 10#@. This optimization means that small integers are always already
-- evaluated in the output for @:p@.
--
-- Since we want this test to work on @integer-simple@ too, we explicitly
-- force the literal.
let ten = 10 :: Integer
:f ten
let i = Just ten
:p i

case i of Just j -> Control.Exception.evaluate j
:p i

:l Test.hs

let s = S1 'a' 'b' 'c'
s
:p s
:sp s
