-- printing of Showables

:set -XExistentialQuantification -XDeriveDataTypeable -XGeneralizedNewtypeDeriving
let f = Just (1.2::Float)
f
:p f

-- With @ghc-bignum@, small integer literals get converted directly into
-- @IS 10#@. This optimization means that small integers are always already
-- evaluated in the output for @:p@.
let ten = 10 :: Integer
:f ten
let i = Just ten
:p i

case i of Just j -> Control.Exception.evaluate j
:p i

:l Test.hs

let s = S1 'a' 'b' 'c'
s
:p s
:sp s
