# Expected GHC config values, keyed by platform key.
#
# Platform key construction:
#   base = "target platform string" from ghc --info  (or config.platform)
#   key  = base
#        + ("-cross"   if cross-compiling)
#        + ("-unreg"   if Unregisterised,
#           "-no_tntc" elif Tables-next-to-code == NO)
#
# When a new platform is encountered the test prints a ready-to-paste entry.


def platform_key(platform, is_cross, is_unreg, no_tntc):
    key = platform
    if is_cross:  key += "-cross"
    if is_unreg:  key += "-unreg"
    elif no_tntc: key += "-no_tntc"
    return key

PINNED_GHC_INFO_FIELDS = [
    "target arch",
    "target os",
    "target platform string",
    "target word size",
    "target word big endian",
    "Tables next to code",
    "Support SMP",
    "Have interpreter",
    "Use interpreter",
    "Have native code generator",
    "Unregisterised",
    "Leading underscore",
    "target has RTS linker",
    "target RTS linker only supports shared libraries",
    "cross compiling",
    "target has GNU nonexec stack",
    "target has subsections via symbols",
    "Target default backend",
]

GHC_INFO_EXPECTED = {

    # ── x86_64 Linux (all distros) ───────────────────────────────────────────
    "x86_64-unknown-linux": {
        "target arch":                                      "ArchX86_64",
        "target os":                                        "OSLinux",
        "target platform string":                           "x86_64-unknown-linux",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "NO",
        "target has GNU nonexec stack":                     "YES",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── x86_64 Linux unregisterised ──────────────────────────────────────────
    "x86_64-unknown-linux-unreg": {
        "target arch":                                      "ArchX86_64",
        "target os":                                        "OSLinux",
        "target platform string":                           "x86_64-unknown-linux",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "NO",
        "Support SMP":                                      "NO",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "NO",
        "Unregisterised":                                   "YES",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "NO",
        "target has GNU nonexec stack":                     "YES",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "compiling via C",
    },

    # ── x86_64 Linux no tables-next-to-code ──────────────────────────────────
    "x86_64-unknown-linux-no_tntc": {
        "target arch":                                      "ArchX86_64",
        "target os":                                        "OSLinux",
        "target platform string":                           "x86_64-unknown-linux",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "NO",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "NO",
        "target has GNU nonexec stack":                     "YES",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── aarch64 Linux native ─────────────────────────────────────────────────
    "aarch64-unknown-linux": {
        "target arch":                                      "ArchAArch64",
        "target os":                                        "OSLinux",
        "target platform string":                           "aarch64-unknown-linux",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "NO",
        "target has GNU nonexec stack":                     "YES",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── aarch64 Linux cross ──────────────────────────────────────────────────
    "aarch64-unknown-linux-cross": {
        "target arch":                                      "ArchAarch64",
        "target os":                                        "OSLinux",
        "target platform string":                           "aarch64-unknown-linux",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "NO",
        "Use interpreter":                                  "NO",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "YES",
        "target has GNU nonexec stack":                     "YES",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── i386 Linux ───────────────────────────────────────────────────────────
    "i386-unknown-linux": {
        "target arch":                                      "ArchX86",
        "target os":                                        "OSLinux",
        "target platform string":                           "i386-unknown-linux",
        "target word size":                                 "4",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "NO",
        "target has GNU nonexec stack":                     "YES",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── aarch64 macOS ────────────────────────────────────────────────────────
    "aarch64-apple-darwin": {
        "target arch":                                      "ArchAArch64",
        "target os":                                        "OSDarwin",
        "target platform string":                           "aarch64-apple-darwin",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "YES",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "NO",
        "target has GNU nonexec stack":                     "NO",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── x86_64 macOS ─────────────────────────────────────────────────────────
    "x86_64-apple-darwin": {
        "target arch":                                      "ArchX86_64",
        "target os":                                        "OSDarwin",
        "target platform string":                           "x86_64-apple-darwin",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "YES",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "NO",
        "target has GNU nonexec stack":                     "NO",
        "target has subsections via symbols":               "YES",
        "Target default backend":                           "native code generator",
    },

    # ── x86_64 FreeBSD ───────────────────────────────────────────────────────
    "x86_64-portbld-freebsd": {
        "target arch":                                      "ArchX86_64",
        "target os":                                        "OSFreeBSD",
        "target platform string":                           "x86_64-portbld-freebsd",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "NO",
        "target has GNU nonexec stack":                     "YES",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── x86_64 Windows native ────────────────────────────────────────────────
    "x86_64-unknown-mingw32": {
        "target arch":                                      "ArchX86_64",
        "target os":                                        "OSMinGW32",
        "target platform string":                           "x86_64-unknown-mingw32",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "NO",
        "target has GNU nonexec stack":                     "NO",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── aarch64 Windows cross ────────────────────────────────────────────────
    "aarch64-unknown-mingw32-cross": {
        "target arch":                                      "ArchAarch64",
        "target os":                                        "OSMinGW32",
        "target platform string":                           "aarch64-unknown-mingw32",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "NO",
        "Use interpreter":                                  "NO",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "YES",
        "target has GNU nonexec stack":                     "NO",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── wasm32 cross ─────────────────────────────────────────────────────────
    "wasm32-unknown-wasi-cross-no_tntc": {
        "target arch":                                      "ArchWasm32",
        "target os":                                        "OSWasi",
        "target platform string":                           "wasm32-unknown-wasi",
        "target word size":                                 "4",
        "target word big endian":                           "NO",
        "Tables next to code":                              "NO",
        "Support SMP":                                      "NO",
        "Have interpreter":                                 "YES",
        "Use interpreter":                                  "YES",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "YES",
        "target has GNU nonexec stack":                     "NO",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── wasm32 cross unregisterised ──────────────────────────────────────────
    "wasm32-unknown-wasi-cross-unreg": {
        "target arch":                                      "ArchWasm32",
        "target os":                                        "OSWasi",
        "target platform string":                           "wasm32-unknown-wasi",
        "target word size":                                 "4",
        "target word big endian":                           "NO",
        "Tables next to code":                              "NO",
        "Support SMP":                                      "NO",
        "Have interpreter":                                 "NO",
        "Use interpreter":                                  "NO",
        "Have native code generator":                       "NO",
        "Unregisterised":                                   "YES",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "YES",
        "target has GNU nonexec stack":                     "NO",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "compiling via C",
    },

    # ── JavaScript cross ─────────────────────────────────────────────────────
    "javascript-unknown-ghcjs-cross": {
        "target arch":                                      "ArchJavaScript",
        "target os":                                        "OSGhcjs",
        "target platform string":                           "javascript-unknown-ghcjs",
        "target word size":                                 "4",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "NO",
        "Have interpreter":                                 "NO",
        "Use interpreter":                                  "NO",
        "Have native code generator":                       "NO",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "NO",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "YES",
        "target has GNU nonexec stack":                     "NO",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "compiling to JavaScript",
    },

    # ── riscv64 Linux cross ──────────────────────────────────────────────────
    "riscv64-unknown-linux-cross": {
        "target arch":                                      "ArchRISCV64",
        "target os":                                        "OSLinux",
        "target platform string":                           "riscv64-unknown-linux",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "NO",
        "Use interpreter":                                  "NO",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "YES",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "YES",
        "target has GNU nonexec stack":                     "YES",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },

    # ── loongarch64 Linux cross ──────────────────────────────────────────────
    "loongarch64-unknown-linux-cross": {
        "target arch":                                      "ArchLoongArch64",
        "target os":                                        "OSLinux",
        "target platform string":                           "loongarch64-unknown-linux",
        "target word size":                                 "8",
        "target word big endian":                           "NO",
        "Tables next to code":                              "YES",
        "Support SMP":                                      "YES",
        "Have interpreter":                                 "NO",
        "Use interpreter":                                  "NO",
        "Have native code generator":                       "YES",
        "Unregisterised":                                   "NO",
        "Leading underscore":                               "NO",
        "target has RTS linker":                            "NO",
        "target RTS linker only supports shared libraries": "NO",
        "cross compiling":                                  "YES",
        "target has GNU nonexec stack":                     "YES",
        "target has subsections via symbols":               "NO",
        "Target default backend":                           "native code generator",
    },
}

TESTSUITE_CONFIG_EXPECTED = {

    # ── x86_64 Linux ─────────────────────────────────────────────────────────
    "x86_64-unknown-linux": {
        "platform":            "x86_64-unknown-linux",
        "arch":                "x86_64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         True,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               False,
    },

    # ── x86_64 Linux unregisterised ──────────────────────────────────────────
    "x86_64-unknown-linux-unreg": {
        "platform":            "x86_64-unknown-linux",
        "arch":                "x86_64",
        "wordsize":            "64",
        "have_ncg":            False,
        "have_interp":         True,
        "unregisterised":      True,
        "tables_next_to_code": False,
        "leading_underscore":  False,
        "target_has_smp":      False,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               False,
    },

    # ── x86_64 Linux no tables-next-to-code ──────────────────────────────────
    "x86_64-unknown-linux-no_tntc": {
        "platform":            "x86_64-unknown-linux",
        "arch":                "x86_64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         True,
        "unregisterised":      False,
        "tables_next_to_code": False,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               False,
    },

    # ── aarch64 Linux native ─────────────────────────────────────────────────
    "aarch64-unknown-linux": {
        "platform":            "aarch64-unknown-linux",
        "arch":                "aarch64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         True,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               False,
    },

    # ── aarch64 Linux cross ──────────────────────────────────────────────────
    "aarch64-unknown-linux-cross": {
        "platform":            "aarch64-unknown-linux",
        "arch":                "aarch64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         False,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               True,
    },

    # ── i386 Linux ───────────────────────────────────────────────────────────
    "i386-unknown-linux": {
        "platform":            "i386-unknown-linux",
        "arch":                "i386",
        "wordsize":            "32",
        "have_ncg":            True,
        "have_interp":         True,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               False,
    },

    # ── aarch64 macOS ────────────────────────────────────────────────────────
    "aarch64-apple-darwin": {
        "platform":            "aarch64-apple-darwin",
        "arch":                "aarch64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         True,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  True,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               False,
    },

    # ── x86_64 macOS ─────────────────────────────────────────────────────────
    "x86_64-apple-darwin": {
        "platform":            "x86_64-apple-darwin",
        "arch":                "x86_64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         True,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  True,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               False,
    },

    # ── x86_64 FreeBSD ───────────────────────────────────────────────────────
    "x86_64-portbld-freebsd": {
        "platform":            "x86_64-portbld-freebsd",
        "arch":                "x86_64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         True,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               False,
    },

    # ── x86_64 Windows native ────────────────────────────────────────────────
    "x86_64-unknown-mingw32": {
        "platform":            "x86_64-unknown-mingw32",
        "arch":                "x86_64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         True,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               False,
    },

    # ── aarch64 Windows cross ────────────────────────────────────────────────
    "aarch64-unknown-mingw32-cross": {
        "platform":            "aarch64-unknown-mingw32",
        "arch":                "aarch64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         False,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               True,
    },

    # ── wasm32 cross ─────────────────────────────────────────────────────────
    "wasm32-unknown-wasi-cross-no_tntc": {
        "platform":            "wasm32-unknown-wasi",
        "arch":                "wasm32",
        "wordsize":            "32",
        "have_ncg":            True,
        "have_interp":         True,
        "unregisterised":      False,
        "tables_next_to_code": False,
        "leading_underscore":  False,
        "target_has_smp":      False,
        "have_RTS_linker":     True,
        "interp_force_dyn":    True,
        "cross":               True,
    },

    # ── wasm32 cross unregisterised ──────────────────────────────────────────
    "wasm32-unknown-wasi-cross-unreg": {
        "platform":            "wasm32-unknown-wasi",
        "arch":                "wasm32",
        "wordsize":            "32",
        "have_ncg":            False,
        "have_interp":         False,
        "unregisterised":      True,
        "tables_next_to_code": False,
        "leading_underscore":  False,
        "target_has_smp":      False,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               True,
    },

    # ── JavaScript cross ─────────────────────────────────────────────────────
    "javascript-unknown-ghcjs-cross": {
        "platform":            "javascript-unknown-ghcjs",
        "arch":                "javascript",
        "wordsize":            "32",
        "have_ncg":            False,
        "have_interp":         False,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      False,
        "have_RTS_linker":     False,
        "interp_force_dyn":    False,
        "cross":               True,
    },

    # ── riscv64 Linux cross ──────────────────────────────────────────────────
    "riscv64-unknown-linux-cross": {
        "platform":            "riscv64-unknown-linux",
        "arch":                "riscv64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         False,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     True,
        "interp_force_dyn":    False,
        "cross":               True,
    },

    # ── loongarch64 Linux cross ──────────────────────────────────────────────
    "loongarch64-unknown-linux-cross": {
        "platform":            "loongarch64-unknown-linux",
        "arch":                "loongarch64",
        "wordsize":            "64",
        "have_ncg":            True,
        "have_interp":         False,
        "unregisterised":      False,
        "tables_next_to_code": True,
        "leading_underscore":  False,
        "target_has_smp":      True,
        "have_RTS_linker":     False,
        "interp_force_dyn":    False,
        "cross":               True,
    },
}
