:set -v1
System.IO.writeFile "A.hs" "module A where { import B; }"
System.IO.writeFile "B.hs" "module B where { type T = Int; }"
-- hack: avoid the need for sleep by using specific timestamps:
:! touch -t 01010000 A.hs
:! touch -t 01010000 B.hs
:load A
System.IO.writeFile "A.hs" "module A where { import B; oops }"
:! touch -t 01010001 A.hs
:reload
-- B should still be loaded
:module *B
System.IO.writeFile "A.hs" "module A where { import B; }"
:! touch -t 01010002 A.hs
:reload
-- should not have to reload B
