-- solely for backward-compatibility with pre-2.00 GHC systems.

module PreludeGlaST (
	Array(..), -- NB: makes internals visible
	MutableVar,
	ST,
	ByteArray,
	MutableArray,
	MutableByteArray,
	PrimIO,
	Addr, Word,
	CCallable(..), CReturnable(..),

	boundsOfArray,
	boundsOfByteArray,
	fixPrimIO,
	fixST,
	forkPrimIO,
	forkST,
	freezeAddrArray,
	freezeArray,
	freezeCharArray,
	freezeDoubleArray,
	freezeFloatArray,
	freezeIntArray,
	indexAddrArray,
	indexAddrOffAddr,
	indexCharArray,
	indexCharOffAddr,
	indexDoubleArray,
	indexDoubleOffAddr,
	indexFloatArray,
	indexFloatOffAddr,
	indexIntArray,
	indexIntOffAddr,
	ioToST,
	listPrimIO,
	listST,
	mapAndUnzipPrimIO,
	mapAndUnzipST,
	mapPrimIO,
	mapST,
	newAddrArray,
	newArray,
	newCharArray,
	newDoubleArray,
	newFloatArray,
	newIntArray,
	newVar,
	readAddrArray,
	readArray,
	readCharArray,
	readDoubleArray,
	readFloatArray,
	readIntArray,
	readVar,
	returnPrimIO,
	returnST,
	returnStrictlyST,
	primIOToIO,
	ioToPrimIO,
	sameMutableArray,
	sameMutableByteArray,
	sameVar,
	seqPrimIO,
	seqST,
	seqStrictlyST,
	stToIO,
	thawArray,
	thenPrimIO,
	thenST,
	thenStrictlyST,
	unsafeFreezeArray,
	unsafeFreezeByteArray,
	unsafeInterleavePrimIO,
	unsafeInterleaveST,
	unsafePerformPrimIO,
	writeAddrArray,
	writeArray,
	writeCharArray,
	writeDoubleArray,
	writeFloatArray,
	writeIntArray,
	writeVar
    ) where

import GHCbase
