
test('layout001', [], makefile_test, ['layout001'])

test('layout002', [], makefile_test, ['layout002'])

test('layout003', [], makefile_test, ['layout003'])

test('layout004', [], makefile_test, ['layout004'])

test('layout005', [], makefile_test, ['layout005'])

test('layout006', [], makefile_test, ['layout006'])

test('layout007', [req_interp], makefile_test, ['layout007'])

test('layout008', [], makefile_test, ['layout008'])

test('layout009', [], makefile_test, ['layout009'])
