name: Test Hadrian Simple

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hadrian-test:
    runs-on: ubuntu-latest
    env:
      GHC_FLAGS: -Werror
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test basic shell commands
        run: |
          echo "Testing basic functionality..."
          ls -la
          pwd
          echo "Workflow is working!"
      - name: Test Hadrian setup (without git operations)
        run: |
          echo 'package hadrian' > hadrian/cabal.project.local || echo "Directory doesn't exist, creating..."
          mkdir -p hadrian
          echo 'package hadrian' > hadrian/cabal.project.local
          echo '  ghc-options: -Werror' >> hadrian/cabal.project.local
          cat hadrian/cabal.project.local
