name: Test Hadrian GHC-in-GHCi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hadrian-ghc-in-ghci:
    runs-on: ubuntu-latest
    env:
      GHC_FLAGS: -Werror
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fix git repository for local testing
        run: |
          if [ ! -d .git ]; then
            git init .
            git add .
            git commit -m "Initial commit for local testing"
          fi
      - name: Clean repository
        run: |
          git clean -xdf
          git submodule foreach git clean -xdf
      - name: Setup CI environment
        run: . .gitlab/ci.sh setup
      - name: Configure build
        run: . .gitlab/ci.sh configure
      - name: Setup Hadrian project
        run: |
          echo 'package hadrian' > hadrian/cabal.project.local
          echo '  ghc-options: -Werror' >> hadrian/cabal.project.local
      - name: Test GHC-in-GHCi
        run: |
          export CORES="$(mk/detect-cpu-count.sh)"
          echo ":q" | HADRIAN_ARGS=-j$CORES hadrian/ghci -j$CORES | tail -n2 | grep "Ok,"
