TOP = ../..
include $(TOP)/mk/boilerplate.mk

STDIN_FILE = big.cor

# don't: -poscript ./anna.postscript
# This just sums the output to save including the entire output file
# in the repository, but 'sum' differs from machine to machine. --SDM

include $(TOP)/mk/target.mk

