:unset +s
:unset +t
-- A small multi-module program, with 4 modules, A, B, C, D.  B & C
-- depend on D, and A depends on B & C.
--
-- This test will try various combinations of compiled and interpreted
-- versions of each module, and make sure each combination behaves
-- sensibly.

-- clean up
:!rm -f *.o *.hi
:!cp D1.hs D.hs

putStrLn "Run 1"
:load A
:type a
a 42

putStrLn "Run 2"
-- sigh; sleep 1, because the filesystem only stores times in seconds
:!sleep 1; cp D2.hs D.hs
:reload
:type (A.a,B.b,C.c,D.d)
a 42

putStrLn "Run 3"
-- compile D, check that :reload doesn't pick it up
:!"$HC" $HC_OPTS $ghciWayFlags -c D.hs
:reload
:type (A.a,B.b,C.c,D.d)
a 42

putStrLn "Run 4"
-- pick up the compiled D now, with :load
:load A
:type (A.a,B.b,C.c,D.d)
a 42

putStrLn "Run 5"
-- D,C compiled
:!"$HC" $HC_OPTS $ghciWayFlags -c C.hs
:load A
:type (A.a,B.b,C.c,D.d)
a 42

putStrLn "Run 6"
-- D,C,B compiled
:!"$HC" $HC_OPTS $ghciWayFlags -c B.hs
:load A
:type (A.a,B.b,C.c,D.d)
a 42

putStrLn "Run 7"
-- D,C,B,A compiled
:!"$HC" $HC_OPTS $ghciWayFlags -c A.hs
:load A
:type (A.a,B.b,C.c,D.d)
a 42

putStrLn "Run 8"
-- D,C,A compiled  (better not use A.o)
:!rm B.o
:load A
:type (A.a,B.b,C.c,D.d)
a 42

putStrLn "Run 9"
-- D,A compiled  (better not use A.o)
:!rm C.o
:load A
:type (A.a,B.b,C.c,D.d)
a 42

putStrLn "Run 10"
-- A compiled  (better not use A.o)
:!rm D.o
:load A
:type (A.a,B.b,C.c,D.d)
a 42

putStrLn "Run 11"
-- A,B,C compiled (better not use A.o, B.o, C.o)
:!"$HC" $HC_OPTS $ghciWayFlags --make -v0 A
:!rm D.o
:load A
:type (A.a,B.b,C.c,D.d)
a 42
