name: 'Setup GHC Environment'
description: 'Set up the common GHC build environment'

runs:
  using: 'composite'
  steps:
    # - name: Install system dependencies
    #   shell: bash
    #   run: |
    #     apt-get update
    #     apt-get install build-essential git autoconf python3 libgmp-dev libnuma-dev libncurses-dev -y

    - name: Setup Cabal
      shell: bash
      run: |
        git reset --hard
        git clean -xdf
        git submodule foreach git clean -xdf
        git submodule update --init
        cabal update
        cabal install happy-1.20.1.1 --overwrite-policy=always
        cabal install alex
        export PATH="/home/ghcbuild/.local/bin:$PATH"
        . .gitlab/ci.sh setup
        . .gitlab/ci.sh configure

    # - name: Setup Hadrian project
    #   shell: bash
    #   run: |
    #     echo 'package hadrian' > hadrian/cabal.project.local
