:unset +s
:unset +t
-- A small multi-module program, with 4 modules, Main, B, C, D.  B & C
-- depend on D, and A depends on B & C.
-- 
-- This test will try various combinations of compiled and interpreted
-- versions of each module, and make sure each combination behaves
-- sensibly.

:l ../shell.hs
:def shell (\s -> do shell s; return "")

-- clean up
:shell rm -f *.o *.hi
:shell cp D1.hs D.hs

:load A
:type a
a 42

-- sigh; sleep 1, because the filesystem only stores times in seconds
:shell sleep 1; cp D2.hs D.hs
:reload
:type (Main.a,B.b,C.c,D.d)
a 42

-- compile D, check that :reload doesn't pick it up
:shell $HC $HC_OPTS -c D.hs
:reload
:type (Main.a,B.b,C.c,D.d)
a 42

-- pick up the compiled D now, with :load
:load A
:type (Main.a,B.b,C.c,D.d)
a 42

-- D,C compiled
:shell $HC $HC_OPTS -c C.hs
:load A
:type (Main.a,B.b,C.c,D.d)
a 42

-- D,C,B compiled
:shell $HC $HC_OPTS -c B.hs
:load A
:type (Main.a,B.b,C.c,D.d)
a 42

-- D,C,B,A compiled
:shell $HC $HC_OPTS -c A.hs
:load A
:type (Main.a,B.b,C.c,D.d)
a 42

-- D,C,A compiled  (better not use A.o)
:shell rm B.o
:load A
:type (Main.a,B.b,C.c,D.d)
a 42

-- D,A compiled  (better not use A.o)
:shell rm C.o
:load A
:type (Main.a,B.b,C.c,D.d)
a 42

-- A compiled  (better not use A.o)
:shell rm D.o
:load A
:type (Main.a,B.b,C.c,D.d)
a 42

-- A,B,C compiled (better not use A.o, B.o, C.o)
:shell $HC $HC_OPTS --make -v0 A
:shell rm D.o
:load A
:type (Main.a,B.b,C.c,D.d)
a 42
