#!/usr/bin/env python
# -*- coding: utf-8 -*-

from typing import Optional, NamedTuple
import textwrap

class Thing(NamedTuple):
    name: str
    rep_ty: str
    desc: str
    width: Optional[int]

MACH_WORD = None

things = [
    # (name, representation type, human description, width)
    #
    # width in bytes.
    # width == None denotes machine word

    Thing("Char",      "Char#",        "8-bit character",                       1),
    Thing("WideChar",  "Char#",        "32-bit character",                      4),
    Thing("Int",       "Int#",         "word-sized integer",                    MACH_WORD),
    Thing("Word",      "Word#",        "word-sized unsigned integer",           MACH_WORD),
    Thing("Addr",      "Addr#",        "machine address",                       MACH_WORD),
    Thing("Float",     "Float#",       "single-precision floating-point value", 4),
    Thing("Double",    "Double#",      "double-precision floating-point value", 8),
    Thing("StablePtr", "StablePtr# a", "{\\tt StablePtr#} value",               MACH_WORD),
]

# TODO: Eventually when the sized integer primops use proper unboxed types we
# should rather do:
#
#for n in [8,16,32,64]:
#    things += [ Thing(f"Int{n}",  f"Int{n}#",  f"{n}-bit signed integer",   n // 8) ]
#
#for n in [8,16,32,64]:
#    things += [ Thing(f"Word{n}", f"Word{n}#", f"{n}-bit unsigned integer", n // 8) ]

things += [
    Thing("Int8",   "Int#",  "8-bit signed integer",  1),
    Thing("Int16",  "Int#",  "16-bit signed integer", 2),
    Thing("Int32",  "INT32", "32-bit signed integer", 4),
    Thing("Int64",  "INT64", "64-bit signed integer", 8),

    Thing("Word8",  "Word#",  "8-bit unsigned integer",  1),
    Thing("Word16", "Word#",  "16-bit unsigned integer", 2),
    Thing("Word32", "WORD32", "32-bit unsigned integer", 4),
    Thing("Word64", "WORD64", "64-bit unsigned integer", 8),
]

def pretty_offset(n: Optional[int]) -> str:
    if n == MACH_WORD:
        return 'machine words'
    elif n == 1:
        return 'bytes'
    else:
        return f'{n}-byte words'

def print_block(template: str, **kwargs) -> None:
    print(textwrap.dedent(template.format(**kwargs)).lstrip())

def header(s: str):
    print('')
    print_block('''
        ------------------------------------
        -- {s}
        ------------------------------------
    ''', s=s)


header("ByteArray# operations")

print('''
-- Do not edit. This file is generated by utils/genprimops/gen_bytearray_ops.py.
-- To regenerate run,
--
--      python3 utils/genprimops/gen_bytearray_ops.py > compiler/GHC/Builtin/bytearray-ops.txt.pp
''')

header('aligned index operations')
for t in things:
    offset = pretty_offset(t.width)
    print_block('''
        primop IndexByteArrayOp_{name} "index{name}Array#" GenPrimOp
           ByteArray# -> Int# -> {rep_ty}
           {{Read a {desc}; offset in {offset}.}}
           with can_fail = True
    ''', offset = offset, **t._asdict())

header('unaligned index operations')
for t in things:
    print_block('''
        primop IndexByteArrayOp_Word8As{name} "indexWord8ArrayAs{name}#" GenPrimOp
           ByteArray# -> Int# -> {rep_ty}
           {{Read a {desc}; offset in bytes.}}
           with can_fail = True
    ''', **t._asdict())

header('aligned read operations')
for t in things:
    offset = pretty_offset(t.width)
    print_block('''
        primop ReadByteArrayOp_{name} "read{name}Array#" GenPrimOp
           MutableByteArray# s -> Int# -> State# s -> (# State# s, {rep_ty} #)
           {{Read a {desc}; offset in {offset}.}}
           with has_side_effects = True
                can_fail = True
    ''', offset = offset, **t._asdict())

header('unaligned read operations')
for t in things:
    print_block('''
        primop ReadByteArrayOp_Word8As{name} "readWord8ArrayAs{name}#" GenPrimOp
           MutableByteArray# s -> Int# -> State# s -> (# State# s, {rep_ty} #)
           {{Read a {desc}; offset in bytes.}}
           with has_side_effects = True
                can_fail = True
    ''', **t._asdict())

header('aligned write operations')
for t in things:
    offset = pretty_offset(t.width)
    print_block('''
        primop WriteByteArrayOp_{name} "write{name}Array#" GenPrimOp
           MutableByteArray# s -> Int# -> {rep_ty} -> State# s -> State# s
           {{Write a {desc}; offset in {offset}.}}
           with has_side_effects = True
                can_fail = True
    ''', offset = offset, **t._asdict())

header('unaligned write operations')
for t in things:
    print_block('''
        primop WriteByteArrayOp_Word8As{name} "writeWord8ArrayAs{name}#" GenPrimOp
           MutableByteArray# s -> Int# -> {rep_ty} -> State# s -> State# s
           {{Write a {desc}; offset in bytes.}}
           with has_side_effects = True
                can_fail = True
    ''', **t._asdict())

