#-----------------------------------------------------------------------------
# $Id: Makefile,v 1.2 1998/12/02 13:20:22 simonm Exp $

TOP=../..
include $(TOP)/mk/boilerplate.mk

SGML_DOC = libs

include $(TOP)/mk/target.mk
