
include ($confdir ++ "/../vanilla-test.T")

-- Args to vtc are: extra compile flags

test "rn003" { vtc("") }
test "rn005" { vtc("") }
test "rn006" { vtc("") }
test "rn009" { vtc("") }
test "rn010" { vtc("") }
test "rn011" { vtc("") }
test "rn012" { vtc("") }
test "rn013" { vtc("") }
test "rn017" { vtc("") }
test "rn019" { vtc("") }
test "rn020" { vtc("") }
test "rn022" { vtc("") }
test "rn023" { vtc("") }
test "rn024" { vtc("") }
test "rn025" { vtc("") }
test "rn026" { vtc("") }
test "rn027" { vtc("") }
test "rn028" { vtc("") }
test "rn029" { vtc("") }
test "rn030" { vtc("") }
test "rn031" { vtc("") }
test "rn032" { vtc("") }
test "rn033" { vtc("") }
test "rn034" { vtc("") }
test "rn035" { vtc("") }
test "rn036" { vtc("") }

-- really a mulit-module test:
test "Rn037Help" { vtc("") }
test "rn037"     { vtc("") }

test "timing001" { vtc("") }
test "timing002" { vtc("") }
test "timing003" { vtc("") }
