{-
(c) The University of Glasgow 2006
(c) The GRASP/AQUA Project, Glasgow University, 1992-1998
-}

{-# LANGUAGE CPP #-}
{-# LANGUAGE PatternSynonyms #-}

-- |
-- Export /only/ the 'RdrName' data-type.
--
-- Since 'RdrName' is an integral data-type found in many places throughout
-- the compiler, importing a module which exposes 'RdrName' can cause module
-- import cycles. By having a dedicated module which exports the bare minimum
-- necessary to expose the data-type definition, these module import cycles
-- can easily be avoided!
module GHC.Types.Name.RdrName (
        -- * The main type
        RdrName(..),
        WithUserRdr(..),
        isExact_maybe,
        rdrNameOcc,
  ) where

import GHC.Prelude

import GHC.Types.Name
import GHC.Unit.Module
import GHC.Utils.Outputable

import Data.Data
import qualified Data.Semigroup as S

{-
************************************************************************
*                                                                      *
\subsection{The main data type}
*                                                                      *
************************************************************************
-}

-- | Reader Name
--
-- Do not use the data constructors of RdrName directly: prefer the family
-- of functions that creates them, such as 'mkRdrUnqual'
--
-- - Note: A Located RdrName will only have API Annotations if it is a
--         compound one,
--   e.g.
--
-- > `bar`
-- > ( ~ )
--
data RdrName
  = Unqual OccName
        -- ^ Unqualified  name
        --
        -- Used for ordinary, unqualified occurrences, e.g. @x@, @y@ or @Foo@.
        -- Create such a 'RdrName' with 'mkRdrUnqual'

  | Qual ModuleName OccName
        -- ^ Qualified name
        --
        -- A qualified name written by the user in
        -- /source/ code.  The module isn't necessarily
        -- the module where the thing is defined;
        -- just the one from which it is imported.
        -- Examples are @Bar.x@, @Bar.y@ or @Bar.Foo@.
        -- Create such a 'RdrName' with 'mkRdrQual'

  | Orig Module OccName
        -- ^ Original name
        --
        -- An original name; the module is the /defining/ module.
        -- This is used when GHC generates code that will be fed
        -- into the renamer (e.g. from deriving clauses), but where
        -- we want to say \"Use Prelude.map dammit\". One of these
        -- can be created with 'mkOrig'

  | Exact Name
        -- ^ Exact name
        --
        -- We know exactly the 'Name'. This is used:
        --
        --  (1) When the parser parses built-in syntax like @[]@
        --      and @(,)@, but wants a 'RdrName' from it
        --
        --  (2) By Template Haskell, when TH has generated a unique name
        --
        -- Such a 'RdrName' can be created by using 'getRdrName' on a 'Name'
  deriving Data

{-
************************************************************************
*                                                                      *
\subsection{Instances}
*                                                                      *
************************************************************************
-}

instance Eq RdrName where
  (Exact n1)    == (Exact n2)    = n1==n2
    -- Convert exact to orig
  (Exact n1)    == r2@(Orig _ _) = nukeExact n1 == r2
  r1@(Orig _ _) == (Exact n2)    = r1 == nukeExact n2

  (Orig m1 o1)  == (Orig m2 o2)  = m1==m2 && o1==o2
  (Qual m1 o1)  == (Qual m2 o2)  = m1==m2 && o1==o2
  (Unqual o1)   == (Unqual o2)   = o1==o2
  _             == _             = False

instance HasOccName RdrName where
  occName = rdrNameOcc

instance Ord RdrName where
  a <= b = case (a `compare` b) of { LT -> True;  EQ -> True;  GT -> False }
  a <  b = case (a `compare` b) of { LT -> True;  EQ -> False; GT -> False }
  a >= b = case (a `compare` b) of { LT -> False; EQ -> True;  GT -> True  }
  a >  b = case (a `compare` b) of { LT -> False; EQ -> False; GT -> True  }

    -- Exact < Unqual < Qual < Orig
    -- [Note: Apr 2004] We used to use nukeExact to convert Exact to Orig
    --      before comparing so that Prelude.map == the exact Prelude.map, but
    --      that meant that we reported duplicates when renaming bindings
    --      generated by Template Haskell; e.g
    --      do { n1 <- newName "foo"; n2 <- newName "foo";
    --           <decl involving n1,n2> }
    --      I think we can do without this conversion
  compare (Exact n1) (Exact n2) = n1 `compare` n2
  compare (Exact _)  _          = LT

  compare (Unqual _)   (Exact _)    = GT
  compare (Unqual o1)  (Unqual  o2) = o1 `compare` o2
  compare (Unqual _)   _            = LT

  compare (Qual _ _)   (Exact _)    = GT
  compare (Qual _ _)   (Unqual _)   = GT
  compare (Qual m1 o1) (Qual m2 o2) = compare o1 o2 S.<> compare m1 m2
  compare (Qual _ _)   (Orig _ _)   = LT

  compare (Orig m1 o1) (Orig m2 o2) = compare o1 o2 S.<> compare m1 m2
  compare (Orig _ _)   _            = GT

instance Outputable RdrName where
    ppr (Exact name)   = ppr name
    ppr (Unqual occ)   = ppr occ
    ppr (Qual mod occ) = ppr mod <> dot <> ppr occ
    ppr (Orig mod occ) = getPprStyle (\sty -> pprModulePrefix sty mod Nothing occ <> ppr occ)

instance OutputableBndr RdrName where
    pprBndr _ n
        | isTvOcc (rdrNameOcc n) = char '@' <> ppr n
        | otherwise              = ppr n

    pprInfixOcc  rdr = pprInfixVar  (isSymOcc (rdrNameOcc rdr)) (ppr rdr)
    pprPrefixOcc rdr
      | Just name <- isExact_maybe rdr = pprPrefixName name
             -- pprPrefixName has some special cases, so
             -- we delegate to them rather than reproduce them
      | otherwise = pprPrefixVar (isSymOcc (rdrNameOcc rdr)) (ppr rdr)

isExact_maybe :: RdrName -> Maybe Name
isExact_maybe (Exact n) = Just n
isExact_maybe _         = Nothing

nukeExact :: Name -> RdrName
nukeExact n
  | isExternalName n = Orig (nameModule n) (nameOccName n)
  | otherwise        = Unqual (nameOccName n)

rdrNameOcc :: RdrName -> OccName
rdrNameOcc (Qual _ occ) = occ
rdrNameOcc (Unqual occ) = occ
rdrNameOcc (Orig _ occ) = occ
rdrNameOcc (Exact name) = nameOccName name

rdrQual_maybe :: RdrName -> Maybe ModuleName
rdrQual_maybe = \case
  Qual q _ -> Just q
  _        -> Nothing

--------------------------------------------------------------------------------
-- Preserving user-written qualification

-- | 'WithUserRdr' allows us to keep track of the original user-written
-- 'RdrName', and in particular, any user-written module qualification.
--
-- See Note [IdOcc] in Language.Haskell.Syntax.Extension.
data WithUserRdr a = WithUserRdr RdrName a
  deriving stock (Functor, Foldable, Traversable)

instance NamedThing a => NamedThing (WithUserRdr a) where
  getName (WithUserRdr _rdr a) = getName a
instance Outputable (WithUserRdr Name) where
    ppr (WithUserRdr rdr name) =
      pprName_userQual (rdrQual_maybe rdr) name
instance OutputableBndr (WithUserRdr Name) where
    pprBndr _ (WithUserRdr rdr name) =
      pprName_userQual (rdrQual_maybe rdr) name
    pprInfixOcc :: WithUserRdr Name -> SDoc
    pprInfixOcc  = pprInfixName
    pprPrefixOcc = pprPrefixName
