#! /usr/bin/perl -i.bak

while (<>) {
    # Insert header line
    if ($ARGV ne $oldargv) {
	$ARGV =~ /\d+/;
	$filenum = $&;
	print <<EOTXT;
Reading file "test/runtime/r$filenum.hs":
EOTXT
        $oldargv = $ARGV;
    }

    # Make this script idempotent
    next if /^Reading file "test\/runtime\/r\d+\.hs":/;

    # Fix error messages
    s#test/[A-Za-z]+\d+\.hs#test/runtime/r$filenum.hs#g;

    # Delete trailing line
    s/^Hugs:\[Leaving Hugs\]\n//;

    print;
}
