# NB: don't set `language: haskell` here

# See also https://github.com/hvr/multi-ghc-travis for more information
env:
 - GHCVER=7.0.4 CABALVER=1.16
 # we have to use CABALVER=1.16 for GHC<7.6 as well, as there's
 # no package for earlier cabal versions in the PPA
 - GHCVER=7.4.2 CABALVER=1.16
 - GHCVER=7.6.3 CABALVER=1.16
 - GHCVER=7.8.4 CABALVER=1.18
 - GHCVER=7.10.3 CABALVER=1.22
 - GHCVER=8.0.1 CABALVER=1.24
 - GHCVER=head CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=head CABALVER=head

# Note: the distinction between `before_install` and `install` is not
#       important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version

install:
 - travis_retry cabal update
 - cabal install --only-dependencies
 # we need to install the test-suite and benchmark deps manually as the cabal
 # solver would otherwise complain about cyclic deps
 - cabal install 'test-framework >= 0.3.3' 'test-framework-quickcheck2 >= 0.2.9' 'QuickCheck >= 2.4.0.1' 'ChasingBottoms' 'HUnit' 'test-framework-hunit'

 # If we enable benchmarks, we'll need 'criterion >= 0.4.0 && < 1.2'

# Here starts the actual work to be performed for the package under
# test; any command which exits with a non-zero exit code causes the
# build to fail.
script:
 # -v2 provides useful information for debugging
 - cabal configure -v2 --enable-tests

 # We'd like to
 # --enable-benchmarks
 # but CI time goes through the roof. Maybe there's a way to limit it to just one GHC version?

 # this builds all libraries and executables
 # (including tests/benchmarks)
 - cabal build
 - cabal test

 # tests that a source-distribution can be generated
 - cabal sdist

 # check that the generated source-distribution can be built & installed
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install --force-reinstalls "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi

# EOF
