TOP=../..
include $(TOP)/mk/boilerplate.mk
include $(TOP)/mk/test.mk

LIBDIR := "`'$(TEST_HC)' $(TEST_HC_OPTS) --print-libdir | tr -d '\r'`"

clean:
	rm -f *.o *.hi *.ppr.hs
	rm Ppr003 Ppr004

.PHONY: ppr001
ppr001:
	$(CHECK_PPR)   $(LIBDIR) Ppr001.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr001.hs

.PHONY: ppr002
ppr002:
	$(CHECK_PPR)   $(LIBDIR) Ppr002.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr002.hs

.PHONY: ppr002a
ppr002a:
	$(CHECK_PPR)   $(LIBDIR) Ppr002a.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr002a.hs

.PHONY: ppr003
ppr003:
	$(CHECK_PPR)   $(LIBDIR) Ppr003.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr003.hs

.PHONY: ppr004
ppr004:
	$(CHECK_PPR)   $(LIBDIR) Ppr004.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr004.hs

.PHONY: ppr005
ppr005:
	$(CHECK_PPR)   $(LIBDIR) Ppr005.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr005.hs

.PHONY: ppr006
ppr006:
	$(CHECK_PPR)   $(LIBDIR) Ppr006.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr006.hs

.PHONY: ppr007
ppr007:
	$(CHECK_PPR)   $(LIBDIR) Ppr007.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr007.hs

.PHONY: ppr008
ppr008:
	$(CHECK_PPR)   $(LIBDIR) Ppr008.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr008.hs

.PHONY: ppr009
ppr009:
	$(CHECK_PPR)   $(LIBDIR) Ppr009.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr009.hs

.PHONY: ppr010
ppr010:
	$(CHECK_PPR)   $(LIBDIR) Ppr010.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr010.hs

.PHONY: ppr011
ppr011:
	$(CHECK_PPR)   $(LIBDIR) Ppr011.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr011.hs

.PHONY: ppr012
ppr012:
	$(CHECK_PPR)   $(LIBDIR) Ppr012.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr012.hs

.PHONY: ppr013
ppr013:
	$(CHECK_PPR)   $(LIBDIR) Ppr013.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr013.hs

.PHONY: ppr014
ppr014:
	$(CHECK_PPR)   $(LIBDIR) Ppr014.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr014.hs

.PHONY: ppr015
ppr015:
	$(CHECK_PPR)   $(LIBDIR) Ppr015.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr015.hs

.PHONY: ppr016
ppr016:
	$(CHECK_PPR)   $(LIBDIR) Ppr016.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr016.hs

.PHONY: ppr017
ppr017:
	$(CHECK_PPR)   $(LIBDIR) Ppr017.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr017.hs

.PHONY: ppr018
ppr018:
	$(CHECK_PPR)   $(LIBDIR) Ppr018.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr018.hs

.PHONY: ppr019
ppr019:
	$(CHECK_PPR)   $(LIBDIR) Ppr019.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr019.hs

.PHONY: ppr020
ppr020:
	$(CHECK_PPR)   $(LIBDIR) Ppr020.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr020.hs

.PHONY: ppr021
ppr021:
	$(CHECK_PPR)   $(LIBDIR) Ppr021.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr021.hs

.PHONY: ppr022
ppr022:
	$(CHECK_PPR)   $(LIBDIR) Ppr022.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr022.hs

.PHONY: ppr023
ppr023:
	$(CHECK_PPR)   $(LIBDIR) Ppr023.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr023.hs

.PHONY: ppr024
ppr024:
	$(CHECK_PPR)   $(LIBDIR) Ppr024.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr024.hs

.PHONY: ppr025
ppr025:
	$(CHECK_PPR)   $(LIBDIR) Ppr025.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr025.hs

.PHONY: ppr026
ppr026:
	$(CHECK_PPR)   $(LIBDIR) Ppr026.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr026.hs

.PHONY: ppr027
ppr027:
	$(CHECK_PPR)   $(LIBDIR) Ppr027.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr027.hs

.PHONY: ppr028
ppr028:
	$(CHECK_PPR)   $(LIBDIR) Ppr028.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr028.hs

.PHONY: ppr029
ppr029:
	$(CHECK_PPR)   $(LIBDIR) Ppr029.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr029.hs

.PHONY: ppr030
ppr030:
	$(CHECK_PPR)   $(LIBDIR) Ppr030.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr030.hs

.PHONY: ppr031
ppr031:
	$(CHECK_PPR)   $(LIBDIR) Ppr031.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr031.hs

.PHONY: ppr032
ppr032:
	$(CHECK_PPR)   $(LIBDIR) Ppr032.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr032.hs

.PHONY: ppr033
ppr033:
	$(CHECK_PPR)   $(LIBDIR) Ppr033.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr033.hs

.PHONY: ppr034
ppr034:
	$(CHECK_PPR)   $(LIBDIR) Ppr034.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr034.hs

.PHONY: ppr035
ppr035:
	$(CHECK_PPR)   $(LIBDIR) Ppr035.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr035.hs

.PHONY: ppr036
ppr036:
	$(CHECK_PPR)   $(LIBDIR) Ppr036.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr036.hs

.PHONY: ppr037
ppr037:
	$(CHECK_PPR)   $(LIBDIR) Ppr037.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr037.hs

.PHONY: ppr038
ppr038:
	$(CHECK_PPR)   $(LIBDIR) Ppr038.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr038.hs

.PHONY: ppr039
ppr039:
	$(CHECK_PPR)   $(LIBDIR) Ppr039.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr039.hs

.PHONY: ppr040
ppr040:
	$(CHECK_PPR)   $(LIBDIR) Ppr040.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr040.hs

.PHONY: ppr041
ppr041:
	$(CHECK_PPR)   $(LIBDIR) Ppr041.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr041.hs

.PHONY: ppr042
ppr042:
	$(CHECK_PPR)   $(LIBDIR) Ppr042.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr042.hs

.PHONY: ppr043
ppr043:
	$(CHECK_PPR)   $(LIBDIR) Ppr043.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr043.hs

.PHONY: ppr044
ppr044:
	$(CHECK_PPR)   $(LIBDIR) Ppr044.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr044.hs

.PHONY: ppr045
ppr045:
	$(CHECK_PPR)   $(LIBDIR) Ppr045.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr045.hs

.PHONY: ppr046
ppr046:
	$(CHECK_PPR)   $(LIBDIR) Ppr046.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr046.hs

.PHONY: ppr048
ppr048:
	$(CHECK_PPR)   $(LIBDIR) Ppr048.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr048.hs

.PHONY: ppr049
ppr049:
	$(CHECK_PPR)   $(LIBDIR) Ppr049.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr049.hs

.PHONY: ppr050
ppr050:
	$(CHECK_PPR)   $(LIBDIR) Ppr050.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr050.hs

.PHONY: ppr051
ppr051:
	$(CHECK_PPR)   $(LIBDIR) Ppr051.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr051.hs

.PHONY: ppr052
ppr052:
	$(CHECK_PPR)   $(LIBDIR) Ppr052.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr052.hs

.PHONY: ppr053
ppr053:
	$(CHECK_PPR)   $(LIBDIR) Ppr053.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr053.hs

.PHONY: ppr054
ppr054:
	$(CHECK_PPR)   $(LIBDIR) Ppr054.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr054.hs

.PHONY: ppr055
ppr055:
	$(CHECK_PPR)   $(LIBDIR) Ppr055.hs
	$(CHECK_EXACT) $(LIBDIR) Ppr055.hs

.PHONY: T13199
T13199:
	$(CHECK_PPR)   $(LIBDIR) T13199.hs
	$(CHECK_EXACT) $(LIBDIR) T13199.hs

.PHONY: T13050p
T13050p:
	$(CHECK_PPR)   $(LIBDIR) T13050p.hs
	$(CHECK_EXACT) $(LIBDIR) T13050p.hs

.PHONY: T13550
T13550:
	$(CHECK_PPR)   $(LIBDIR) T13550.hs
	$(CHECK_EXACT) $(LIBDIR) T13550.hs

.PHONY: T13942
T13942:
	$(CHECK_PPR)   $(LIBDIR) T13942.hs
	$(CHECK_EXACT) $(LIBDIR) T13942.hs

.PHONY: T14289
T14289:
	$(CHECK_PPR)   $(LIBDIR) T14289.hs
	$(CHECK_EXACT) $(LIBDIR) T14289.hs

.PHONY: T14289b
T14289b:
	$(CHECK_PPR)   $(LIBDIR) T14289b.hs
	$(CHECK_EXACT) $(LIBDIR) T14289b.hs

.PHONY: T14289c
T14289c:
	$(CHECK_PPR)   $(LIBDIR) T14289c.hs
	$(CHECK_EXACT) $(LIBDIR) T14289c.hs

.PHONY: T14306
T14306:
	$(CHECK_PPR)   $(LIBDIR) T14306.hs
	$(CHECK_EXACT) $(LIBDIR) T14306.hs

.PHONY: T14343
T14343:
	$(CHECK_PPR)   $(LIBDIR) T14343.hs
	$(CHECK_EXACT) $(LIBDIR) T14343.hs

.PHONY: T14343b
T14343b:
	$(CHECK_PPR)   $(LIBDIR) T14343b.hs
	$(CHECK_EXACT) $(LIBDIR) T14343b.hs

.PHONY: RdrNames
RdrNames:
	$(CHECK_PPR)   $(LIBDIR) RdrNames.hs
	$(CHECK_EXACT) $(LIBDIR) RdrNames.hs

.PHONY: StarBinderAnns
StarBinderAnns:
	$(CHECK_PPR)   $(LIBDIR) StarBinderAnns.hs
	$(CHECK_EXACT) $(LIBDIR) StarBinderAnns.hs

.PHONY: Test10255
Test10255:
	$(CHECK_PPR)   $(LIBDIR) Test10255.hs
	$(CHECK_EXACT) $(LIBDIR) Test10255.hs

.PHONY: Test10268
Test10268:
	$(CHECK_PPR)   $(LIBDIR) Test10268.hs
	$(CHECK_EXACT) $(LIBDIR) Test10268.hs

.PHONY: Test10269
Test10269:
	$(CHECK_PPR)   $(LIBDIR) Test10269.hs
	$(CHECK_EXACT) $(LIBDIR) Test10269.hs

.PHONY: Test10276
Test10276:
	$(CHECK_PPR)   $(LIBDIR) Test10276.hs
	$(CHECK_EXACT) $(LIBDIR) Test10276.hs

.PHONY: Test10278
Test10278:
	$(CHECK_PPR)   $(LIBDIR) Test10278.hs
	$(CHECK_EXACT) $(LIBDIR) Test10278.hs

.PHONY: Test10280
Test10280:
	$(CHECK_PPR)   $(LIBDIR) Test10280.hs
	$(CHECK_EXACT) $(LIBDIR) Test10280.hs

.PHONY: Test10307
Test10307:
	$(CHECK_PPR)   $(LIBDIR) Test10307.hs
	$(CHECK_EXACT) $(LIBDIR) Test10307.hs

.PHONY: Test10309
Test10309:
	$(CHECK_PPR)   $(LIBDIR) Test10309.hs
	$(CHECK_EXACT) $(LIBDIR) Test10309.hs

.PHONY: Test10312
Test10312:
	$(CHECK_PPR)   $(LIBDIR) Test10312.hs
	$(CHECK_EXACT) $(LIBDIR) Test10312.hs

.PHONY: Test10313
Test10313:
	$(CHECK_PPR)   $(LIBDIR) Test10313.hs
	$(CHECK_EXACT) $(LIBDIR) Test10313.hs

.PHONY: Test10354
Test10354:
	$(CHECK_PPR)   $(LIBDIR) Test10354.hs
	$(CHECK_EXACT) $(LIBDIR) Test10354.hs

.PHONY: Test10357
Test10357:
	$(CHECK_PPR)   $(LIBDIR) Test10357.hs
	$(CHECK_EXACT) $(LIBDIR) Test10357.hs

.PHONY: Test10358
Test10358:
	$(CHECK_PPR)   $(LIBDIR) Test10358.hs
	$(CHECK_EXACT) $(LIBDIR) Test10358.hs

.PHONY: Test10396
Test10396:
	$(CHECK_PPR)   $(LIBDIR) Test10396.hs
	$(CHECK_EXACT) $(LIBDIR) Test10396.hs

.PHONY: Test10399
Test10399:
	$(CHECK_PPR)   $(LIBDIR) Test10399.hs
	$(CHECK_EXACT) $(LIBDIR) Test10399.hs

.PHONY: Test10598
Test10598:
	$(CHECK_PPR)   $(LIBDIR) Test10598.hs
	$(CHECK_EXACT) $(LIBDIR) Test10598.hs

.PHONY: Test11018
Test11018:
	$(CHECK_PPR)   $(LIBDIR) Test11018.hs
	$(CHECK_EXACT) $(LIBDIR) Test11018.hs

.PHONY: Test11321
Test11321:
	$(CHECK_PPR)   $(LIBDIR) Test11321.hs
	$(CHECK_EXACT) $(LIBDIR) Test11321.hs

.PHONY: Test11332
Test11332:
	$(CHECK_PPR)   $(LIBDIR) Test11332.hs
	$(CHECK_EXACT) $(LIBDIR) Test11332.hs

.PHONY: Test11430
Test11430:
	$(CHECK_PPR)   $(LIBDIR) Test11430.hs
	$(CHECK_EXACT) $(LIBDIR) Test11430.hs

.PHONY: Test12417
Test12417:
	$(CHECK_PPR)   $(LIBDIR) Test12417.hs
	$(CHECK_EXACT) $(LIBDIR) Test12417.hs

.PHONY: Test13163
Test13163:
	$(CHECK_PPR)   $(LIBDIR) Test13163.hs
	$(CHECK_EXACT) $(LIBDIR) Test13163.hs

.PHONY: Test15303
Test15303:
	$(CHECK_PPR)   $(LIBDIR) Test15303.hs
	$(CHECK_EXACT) $(LIBDIR) Test15303.hs

.PHONY: Test16212
Test16212:
	$(CHECK_PPR)   $(LIBDIR) Test16212.hs
	$(CHECK_EXACT) $(LIBDIR) Test16212.hs

.PHONY: Test16230
Test16230:
	$(CHECK_PPR)   $(LIBDIR) Test16230.hs
	$(CHECK_EXACT) $(LIBDIR) Test16230.hs

.PHONY: Test16236
Test16236:
	$(CHECK_PPR)   $(LIBDIR) Test16236.hs
	$(CHECK_EXACT) $(LIBDIR) Test16236.hs

.PHONY: Test16279
Test16279:
	$(CHECK_PPR)   $(LIBDIR) Test16279.hs
	$(CHECK_EXACT) $(LIBDIR) Test16279.hs

.PHONY: Test17388
Test17388:
	$(CHECK_PPR)   $(LIBDIR) Test17388.hs
	$(CHECK_EXACT) $(LIBDIR) Test17388.hs

.PHONY: Test17519
Test17519:
	$(CHECK_PPR)   $(LIBDIR) Test17519.hs
	$(CHECK_EXACT) $(LIBDIR) Test17519.hs

.PHONY: Test15242
Test15242:
	$(CHECK_PPR)   $(LIBDIR) Test15242.hs
	$(CHECK_EXACT) $(LIBDIR) Test15242.hs

.PHONY: AnnotationLet
AnnotationLet:
	$(CHECK_PPR)   $(LIBDIR) AnnotationLet.hs
	$(CHECK_EXACT) $(LIBDIR) AnnotationLet.hs

.PHONY: TestBoolFormula
TestBoolFormula:
	$(CHECK_PPR)   $(LIBDIR) TestBoolFormula.hs
	$(CHECK_EXACT) $(LIBDIR) TestBoolFormula.hs

.PHONY: BundleExport
BundleExport:
	$(CHECK_PPR)   $(LIBDIR) BundleExport.hs
	$(CHECK_EXACT) $(LIBDIR) BundleExport.hs

.PHONY: AnnotationTuple
AnnotationTuple:
	$(CHECK_PPR)   $(LIBDIR) AnnotationTuple.hs
	$(CHECK_EXACT) $(LIBDIR) AnnotationTuple.hs

.PHONY: ListComprehensions
ListComprehensions:
	$(CHECK_PPR)   $(LIBDIR) ListComprehensions.hs
	$(CHECK_EXACT) $(LIBDIR) ListComprehensions.hs

.PHONY: load-main
load-main:
	$(CHECK_PPR)   $(LIBDIR) load-main.hs
	$(CHECK_EXACT) $(LIBDIR) load-main.hs

.PHONY: PprRecordDotSyntax1
PprRecordDotSyntax1:
	$(CHECK_PPR)   $(LIBDIR) PprRecordDotSyntax1.hs
	$(CHECK_EXACT) $(LIBDIR) PprRecordDotSyntax1.hs

.PHONY: PprRecordDotSyntax2
PprRecordDotSyntax2:
	$(CHECK_PPR)   $(LIBDIR) PprRecordDotSyntax2.hs
	$(CHECK_EXACT) $(LIBDIR) PprRecordDotSyntax2.hs

.PHONY: PprRecordDotSyntax3
PprRecordDotSyntax3:
	$(CHECK_PPR)   $(LIBDIR) PprRecordDotSyntax3.hs
	$(CHECK_EXACT) $(LIBDIR) PprRecordDotSyntax3.hs

.PHONY: PprRecordDotSyntax4
PprRecordDotSyntax4:
	$(CHECK_PPR)   $(LIBDIR) PprRecordDotSyntax4.hs
	$(CHECK_EXACT) $(LIBDIR) PprRecordDotSyntax4.hs

.PHONY: PprRecordDotSyntaxA
PprRecordDotSyntaxA:
	$(CHECK_PPR)   $(LIBDIR) PprRecordDotSyntaxA.hs
	$(CHECK_EXACT) $(LIBDIR) PprRecordDotSyntaxA.hs

.PHONY: CommentsTest
CommentsTest:
	$(CHECK_PPR)   $(LIBDIR) CommentsTest.hs
	$(CHECK_EXACT) $(LIBDIR) CommentsTest.hs

.PHONY: InTreeAnnotations1
InTreeAnnotations1:
	$(CHECK_PPR)   $(LIBDIR) InTreeAnnotations1.hs
	$(CHECK_EXACT) $(LIBDIR) InTreeAnnotations1.hs

.PHONY: PprLinearArrow
PprLinearArrow:
	# $(CHECK_PPR)   $(LIBDIR) PprLinearArrow.hs
	$(CHECK_EXACT) $(LIBDIR) PprLinearArrow.hs


.PHONY: Test19784
Test19784:
	$(CHECK_PPR)   $(LIBDIR) Test19784.hs
	$(CHECK_EXACT) $(LIBDIR) Test19784.hs

.PHONY: Test19798
Test19798:
	$(CHECK_PPR)   $(LIBDIR) Test19798.hs
	$(CHECK_EXACT) $(LIBDIR) Test19798.hs

.PHONY: Test19813
Test19813:
	# $(CHECK_PPR)   $(LIBDIR) Test19813.hs
	$(CHECK_EXACT) $(LIBDIR) Test19813.hs

.PHONY: Test19814
Test19814:
	$(CHECK_PPR)   $(LIBDIR) Test19814.hs
	$(CHECK_EXACT) $(LIBDIR) Test19814.hs

.PHONY: Test19821
Test19821:
	$(CHECK_PPR)   $(LIBDIR) Test19821.hs
	$(CHECK_EXACT) $(LIBDIR) Test19821.hs

.PHONY: Test19834
Test19834:
	$(CHECK_PPR)   $(LIBDIR) Test19834.hs
	$(CHECK_EXACT) $(LIBDIR) Test19834.hs

.PHONY: Test19839
Test19839:
	$(CHECK_PPR)   $(LIBDIR) Test19839.hs
	$(CHECK_EXACT) $(LIBDIR) Test19839.hs

.PHONY: Test19840
Test19840:
	$(CHECK_PPR)   $(LIBDIR) Test19840.hs
	$(CHECK_EXACT) $(LIBDIR) Test19840.hs

.PHONY: Test19850
Test19850:
	$(CHECK_PPR)   $(LIBDIR) Test19850.hs
	$(CHECK_EXACT) $(LIBDIR) Test19850.hs

.PHONY: PprCommentsOnly
PprCommentsOnly:
	$(CHECK_PPR)   $(LIBDIR) PprCommentsOnly.hs
	$(CHECK_EXACT) $(LIBDIR) PprCommentsOnly.hs

.PHONY: PprSemis
PprSemis:
	$(CHECK_PPR)   $(LIBDIR) PprSemis.hs
	$(CHECK_EXACT) $(LIBDIR) PprSemis.hs

.PHONY: PprForeignDecl
PprForeignDecl:
	# $(CHECK_PPR)   $(LIBDIR) PprForeignDecl.hs
	$(CHECK_EXACT) $(LIBDIR) PprForeignDecl.hs

.PHONY: PprRoles
PprRoles:
	$(CHECK_PPR)   $(LIBDIR) PprRoles.hs
	$(CHECK_EXACT) $(LIBDIR) PprRoles.hs

.PHONY: PprTypeSynParens
PprTypeSynParens:
	$(CHECK_PPR)   $(LIBDIR) PprTypeSynParens.hs
	$(CHECK_EXACT) $(LIBDIR) PprTypeSynParens.hs

.PHONY: PprEmptyMostlyInst
PprEmptyMostlyInst:
	$(CHECK_PPR)   $(LIBDIR) PprEmptyMostlyInst.hs
	$(CHECK_EXACT) $(LIBDIR) PprEmptyMostlyInst.hs

.PHONY: PprParenFunBind
PprParenFunBind:
	# $(CHECK_PPR)   $(LIBDIR) PprParenFunBind.hs
	$(CHECK_EXACT) $(LIBDIR) PprParenFunBind.hs

.PHONY: PprRecordSemi
PprRecordSemi:
	$(CHECK_PPR)   $(LIBDIR) PprRecordSemi.hs
	$(CHECK_EXACT) $(LIBDIR) PprRecordSemi.hs

.PHONY: PprCompleteSig
PprCompleteSig:
	$(CHECK_PPR)   $(LIBDIR) PprCompleteSig.hs
	$(CHECK_EXACT) $(LIBDIR) PprCompleteSig.hs

.PHONY: PprOverloadedLabels
PprOverloadedLabels:
	$(CHECK_PPR)   $(LIBDIR) PprOverloadedLabels.hs
	$(CHECK_EXACT) $(LIBDIR) PprOverloadedLabels.hs

.PHONY: PprArrows
PprArrows:
	$(CHECK_PPR)   $(LIBDIR) PprArrows.hs
	$(CHECK_EXACT) $(LIBDIR) PprArrows.hs

.PHONY: PprOverloadedRecords
PprOverloadedRecords:
	$(CHECK_PPR)   $(LIBDIR) PprOverloadedRecords.hs
	$(CHECK_EXACT) $(LIBDIR) PprOverloadedRecords.hs

.PHONY: PprArrowLambdaCase
PprArrowLambdaCase:
	$(CHECK_PPR)   $(LIBDIR) PprArrowLambdaCase.hs
	$(CHECK_EXACT) $(LIBDIR) PprArrowLambdaCase.hs

.PHONY: PprRecursiveDo
PprRecursiveDo:
	$(CHECK_PPR)   $(LIBDIR) PprRecursiveDo.hs
	$(CHECK_EXACT) $(LIBDIR) PprRecursiveDo.hs

.PHONY: PprTypeBrackets
PprTypeBrackets:
	$(CHECK_PPR)   $(LIBDIR) PprTypeBrackets.hs
	$(CHECK_EXACT) $(LIBDIR) PprTypeBrackets.hs

.PHONY: PprDynamic
PprDynamic:
	$(CHECK_PPR)   $(LIBDIR) PprDynamic.hs
	$(CHECK_EXACT) $(LIBDIR) PprDynamic.hs

.PHONY: PprEmptyMostly
PprEmptyMostly:
	$(CHECK_PPR)   $(LIBDIR) PprEmptyMostly.hs
	$(CHECK_EXACT) $(LIBDIR) PprEmptyMostly.hs

.PHONY: PprClassParens
PprClassParens:
	$(CHECK_PPR)   $(LIBDIR) PprClassParens.hs
	$(CHECK_EXACT) $(LIBDIR) PprClassParens.hs

.PHONY: PprThAbstractFamily
PprThAbstractFamily:
	$(CHECK_PPR)   $(LIBDIR) PprThAbstractFamily.hs
	$(CHECK_EXACT) $(LIBDIR) PprThAbstractFamily.hs

.PHONY: PprClassTypeFamily
PprClassTypeFamily:
	$(CHECK_PPR)   $(LIBDIR) PprClassTypeFamily.hs
	$(CHECK_EXACT) $(LIBDIR) PprClassTypeFamily.hs

.PHONY: PprT13747
PprT13747:
	$(CHECK_PPR)   $(LIBDIR) PprT13747.hs
	$(CHECK_EXACT) $(LIBDIR) PprT13747.hs

.PHONY: PprBracesSemiDataDecl
PprBracesSemiDataDecl:
	$(CHECK_PPR)   $(LIBDIR) PprBracesSemiDataDecl.hs
	$(CHECK_EXACT) $(LIBDIR) PprBracesSemiDataDecl.hs

.PHONY: PprUnicodeSyntax
PprUnicodeSyntax:
	$(CHECK_PPR)   $(LIBDIR) PprUnicodeSyntax.hs
	$(CHECK_EXACT) $(LIBDIR) PprUnicodeSyntax.hs

.PHONY: PprCommentPlacement2
PprCommentPlacement2:
	$(CHECK_PPR)   $(LIBDIR) PprCommentPlacement2.hs
	$(CHECK_EXACT) $(LIBDIR) PprCommentPlacement2.hs

.PHONY: PprOrPat
PprOrPat:
	$(CHECK_PPR)   $(LIBDIR) PprOrPat.hs
	$(CHECK_EXACT) $(LIBDIR) PprOrPat.hs

.PHONY: PprExportWarn
PprExportWarn:
	$(CHECK_PPR)   $(LIBDIR) PprExportWarn.hs
	$(CHECK_EXACT) $(LIBDIR) PprExportWarn.hs

.PHONY: PprInstanceWarn
PprInstanceWarn:
	$(CHECK_PPR)   $(LIBDIR) PprInstanceWarn.hs
	$(CHECK_EXACT) $(LIBDIR) PprInstanceWarn.hs

.PHONY: Test20243
Test20243:
	$(CHECK_PPR)   $(LIBDIR) Test20243.hs
	$(CHECK_EXACT) $(LIBDIR) Test20243.hs

.PHONY: Test20247
Test20247:
	$(CHECK_PPR)   $(LIBDIR) Test20247.hs
	$(CHECK_EXACT) $(LIBDIR) Test20247.hs


.PHONY: Test20258
Test20258:
	$(CHECK_PPR)   $(LIBDIR) Test20258.hs
	$(CHECK_EXACT) $(LIBDIR) Test20258.hs

.PHONY: Test20297
Test20297:
	$(CHECK_PPR)   $(LIBDIR) Test20297.hs
	$(CHECK_EXACT) $(LIBDIR) Test20297.hs

.PHONY: Test20846
Test20846:
	$(CHECK_PPR)   $(LIBDIR) Test20846.hs
	$(CHECK_EXACT) $(LIBDIR) Test20846.hs

.PHONY: Test20256
Test20256:
	$(CHECK_PPR)   $(LIBDIR) Test20256.hs
	$(CHECK_EXACT) $(LIBDIR) Test20256.hs

.PHONY: Test21355
Test21355:
	$(CHECK_PPR)   $(LIBDIR) Test21355.hs
	$(CHECK_EXACT) $(LIBDIR) Test21355.hs

.PHONY: Test21805
Test21805:
	$(CHECK_PPR)   $(LIBDIR) Test21805.hs
	$(CHECK_EXACT) $(LIBDIR) Test21805.hs

.PHONY: HsDocTy
HsDocTy:
	# See comment on pprWithDocString, this won't round trip
	# $(CHECK_PPR)   $(LIBDIR) HsDocTy.hs
	$(CHECK_EXACT) $(LIBDIR) HsDocTy.hs

.PHONY: Test22765
Test22765:
	$(CHECK_PPR)   $(LIBDIR) Test22765.hs
	$(CHECK_EXACT) $(LIBDIR) Test22765.hs

.PHONY: Test22771
Test22771:
	$(CHECK_PPR)   $(LIBDIR) Test22771.hs
	$(CHECK_EXACT) $(LIBDIR) Test22771.hs

.PHONY: Test23465
Test23465:
	$(CHECK_PPR)   $(LIBDIR) Test23465.hs
	$(CHECK_EXACT) $(LIBDIR) Test23465.hs

.PHONY: Test23887
Test23887:
	$(CHECK_PPR)   $(LIBDIR) Test23887.hs
	$(CHECK_EXACT) $(LIBDIR) Test23887.hs

.PHONY: Test23885
Test23885:
	# ppr is not currently unicode aware
	# $(CHECK_PPR)   $(LIBDIR) Test23885.hs
	$(CHECK_EXACT) $(LIBDIR) Test23885.hs

.PHONY: AnnotationNoListTuplePuns
AnnotationNoListTuplePuns:
	$(CHECK_PPR)   $(LIBDIR) AnnotationNoListTuplePuns.hs
	$(CHECK_EXACT) $(LIBDIR) AnnotationNoListTuplePuns.hs

.PHONY: Test24533
Test24533:
	$(CHECK_PPR)   $(LIBDIR) Test24533.hs
	$(CHECK_EXACT) $(LIBDIR) Test24533.hs

.PHONY: PprLetIn
PprLetIn:
	$(CHECK_PPR)   $(LIBDIR) PprLetIn.hs
	$(CHECK_EXACT) $(LIBDIR) PprLetIn.hs

.PHONY: CaseAltComments
CaseAltComments:
	$(CHECK_PPR)   $(LIBDIR) CaseAltComments.hs
	$(CHECK_EXACT) $(LIBDIR) CaseAltComments.hs

.PHONY: MatchPatComments
MatchPatComments:
	$(CHECK_PPR)   $(LIBDIR) MatchPatComments.hs
	$(CHECK_EXACT) $(LIBDIR) MatchPatComments.hs

.PHONY: Test24748
Test24748:
	$(CHECK_PPR)   $(LIBDIR) Test24748.hs
	$(CHECK_EXACT) $(LIBDIR) Test24748.hs

.PHONY: DataDeclShort
DataDeclShort:
	$(CHECK_PPR)   $(LIBDIR) DataDeclShort.hs
	$(CHECK_EXACT) $(LIBDIR) DataDeclShort.hs

.PHONY: Test24749
Test24749:
	$(CHECK_PPR)   $(LIBDIR) Test24749.hs
	$(CHECK_EXACT) $(LIBDIR) Test24749.hs

.PHONY: Test24754
Test24754:
	$(CHECK_PPR)   $(LIBDIR) Test24754.hs
	$(CHECK_EXACT) $(LIBDIR) Test24754.hs

.PHONY: Test24755
Test24755:
	$(CHECK_PPR)   $(LIBDIR) Test24755.hs
	$(CHECK_EXACT) $(LIBDIR) Test24755.hs

.PHONY: Test24753
Test24753:
	$(CHECK_PPR)   $(LIBDIR) Test24753.hs
	$(CHECK_EXACT) $(LIBDIR) Test24753.hs

.PHONY: Test24771
Test24771:
	$(CHECK_PPR)   $(LIBDIR) Test24771.hs
	$(CHECK_EXACT) $(LIBDIR) Test24771.hs

.PHONY: Test24159
Test24159:
	$(CHECK_PPR)   $(LIBDIR) Test24159.hs
	$(CHECK_EXACT) $(LIBDIR) Test24159.hs

.PHONY: Test25132
Test25132:
	$(CHECK_PPR)   $(LIBDIR) Test25132.hs
	$(CHECK_EXACT) $(LIBDIR) Test25132.hs

.PHONY: Test25454
Test25454:
	$(CHECK_PPR)   $(LIBDIR) Test25454.hs
	$(CHECK_EXACT) $(LIBDIR) Test25454.hs

.PHONY: Test25467
Test25467:
	$(CHECK_PPR)   $(LIBDIR) Test25467.hs
	$(CHECK_EXACT) $(LIBDIR) Test25467.hs

.PHONY: Test25885
Test25885:
	$(CHECK_PPR)   $(LIBDIR) Test25885.hs
	$(CHECK_EXACT) $(LIBDIR) Test25885.hs
