.. -*- rst -*-
   This file contains commonly used link-references
   See also "extlinks" in conf.py

.. _`Package Versioning Policy`:
.. _PVP: http://pvp.haskell.org/

.. _Hackage: http://hackage.haskell.org/

.. _Haskell: http://www.haskell.org/

.. _Haddock: http://www.haskell.org/haddock/

.. _Alex: http://www.haskell.org/alex/

.. _Happy: http://www.haskell.org/happy/

.. _Hoogle: http://www.haskell.org/hoogle/

.. _HsColour: http://www.cs.york.ac.uk/fp/darcs/hscolour/

.. _cpphs: http://projects.haskell.org/cpphs/
